#!/usr/bin/env node
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const guiRoot = path.resolve(scriptDir, "..");
const outputDir = path.join(guiRoot, "app", "public", "assets", "fonts", "google");
const cssOutput = path.join(outputDir, "fonts.css");
const userAgent =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const fontRequests = [
  { family: "Archivo", weights: [400, 430, 500, 600, 700] },
  { family: "IBM Plex Sans", weights: [400, 430, 500, 600, 700] },
  { family: "IBM Plex Mono", weights: [400, 500, 600] },
  { family: "IBM Plex Sans JP", weights: [400, 500, 600, 700] },
  { family: "IBM Plex Sans KR", weights: [400, 500, 600, 700] },
  { family: "IBM Plex Sans Devanagari", weights: [400, 500, 600, 700] },
  { family: "IBM Plex Sans Arabic", weights: [400, 500, 600, 700] },
  { family: "IBM Plex Sans Thai", weights: [400, 500, 600, 700] },
  { family: "IBM Plex Sans Hebrew", weights: [400, 500, 600, 700] },
  { family: "Anek Bangla", weights: [400, 500, 600, 700] },
  { family: "LXGW Marker Gothic", weights: [] },
  { family: "Spline Sans", weights: [400, 500, 600, 700] },
  { family: "Chivo", weights: [400, 500, 600, 700] },
  { family: "Hanken Grotesk", weights: [400, 500, 600, 700] },
  { family: "Azeret Mono", weights: [400, 500, 600] },
  { family: "Sometype Mono", weights: [400, 500, 600] },
  { family: "Fragment Mono", weights: [] },
  { family: "Reddit Mono", weights: [400, 500, 600] },
];

const unavailableOnGoogleFonts = ["IBM Plex Sans SC"];

function googleCssUrl({ family, weights }) {
  const familyValue = weights.length
    ? `${family.replaceAll(" ", "+")}:wght@${weights.join(";")}`
    : family.replaceAll(" ", "+");
  return `https://fonts.googleapis.com/css2?family=${familyValue}&display=swap`;
}

function safeFileName(url, index) {
  const parsed = new URL(url);
  const rawName = path.basename(parsed.pathname).replace(/[^a-zA-Z0-9._-]/gu, "_");
  const extension = path.extname(rawName) || ".woff2";
  const base = path.basename(rawName, extension).slice(0, 72) || "font";
  return `${String(index).padStart(3, "0")}-${base}${extension}`;
}

async function fetchText(url) {
  const response = await fetchWithRetry(url);
  if (!response.ok) {
    throw new Error(`${url} returned HTTP ${response.status}`);
  }
  return response.text();
}

async function fetchBytes(url) {
  const response = await fetchWithRetry(url);
  if (!response.ok) {
    throw new Error(`${url} returned HTTP ${response.status}`);
  }
  return Buffer.from(await response.arrayBuffer());
}

async function fetchWithRetry(url) {
  let lastError;
  for (let attempt = 1; attempt <= 4; attempt += 1) {
    try {
      return await fetch(url, { headers: { "user-agent": userAgent } });
    } catch (error) {
      lastError = error;
      await new Promise((resolve) => setTimeout(resolve, 250 * attempt));
    }
  }
  throw new Error(
    `${url} failed after retries: ${lastError instanceof Error ? lastError.message : String(lastError)}`,
  );
}

async function mapWithConcurrency(items, concurrency, mapper) {
  let index = 0;
  const workers = Array.from({ length: Math.min(concurrency, items.length) }, async () => {
    while (index < items.length) {
      const item = items[index];
      index += 1;
      await mapper(item);
    }
  });
  await Promise.all(workers);
}

async function main() {
  if (process.env.TURA_GUI_SKIP_FONT_INSTALL === "1") {
    console.log("Skipping GUI font install because TURA_GUI_SKIP_FONT_INSTALL=1.");
    return;
  }

  await mkdir(outputDir, { recursive: true });

  let existingCss = "";
  try {
    existingCss = await readFile(cssOutput, "utf8");
  } catch {
    existingCss = "";
  }
  if (existingCss.includes("Generated by apps/gui/scripts/install-fonts.mjs")) {
    console.log("GUI fonts already installed.");
    return;
  }

  await rm(outputDir, { recursive: true, force: true });
  await mkdir(outputDir, { recursive: true });

  const downloaded = new Map();
  const cssParts = [
    "/* Generated by apps/gui/scripts/install-fonts.mjs. Do not edit by hand. */",
    "/* Google Fonts does not currently serve IBM Plex Sans SC; LXGW Marker Gothic is the local Google Fonts CJK fallback. */",
    "",
  ];
  let fileIndex = 1;

  for (const request of fontRequests) {
    const cssUrl = googleCssUrl(request);
    const remoteCss = await fetchText(cssUrl);
    const rewrittenCss = remoteCss.replace(
      /url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/gu,
      (match, fontUrl) => {
        let localName = downloaded.get(fontUrl);
        if (!localName) {
          localName = safeFileName(fontUrl, fileIndex);
          downloaded.set(fontUrl, localName);
          fileIndex += 1;
        }
        return `url("./${localName}")`;
      },
    );
    cssParts.push(`/* ${request.family} */`, rewrittenCss.trim(), "");
  }

  await mapWithConcurrency(Array.from(downloaded.entries()), 6, async ([fontUrl, localName]) => {
    await writeFile(path.join(outputDir, localName), await fetchBytes(fontUrl));
  });
  await writeFile(cssOutput, `${cssParts.join("\n").trim()}\n`, "utf8");

  console.log(
    `Installed ${downloaded.size} GUI font files from Google Fonts into ${path.relative(guiRoot, outputDir)}.`,
  );
  console.warn(
    `Google Fonts unavailable family kept as CSS preference only: ${unavailableOnGoogleFonts.join(", ")}.`,
  );
}

main().catch((error) => {
  console.error(
    `Failed to install GUI fonts: ${error instanceof Error ? error.message : String(error)}`,
  );
  process.exit(1);
});
